# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_property_taxes import RentcastPropertyRecords200ResponseInnerPropertyTaxes

class TestRentcastPropertyRecords200ResponseInnerPropertyTaxes(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerPropertyTaxes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerPropertyTaxes:
        """Test RentcastPropertyRecords200ResponseInnerPropertyTaxes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerPropertyTaxes`
        """
        model = RentcastPropertyRecords200ResponseInnerPropertyTaxes()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerPropertyTaxes(
                var_2019 = rentcast_client.models.property_records_200_response_inner_property_taxes_2019.property_records_200_response_inner_propertyTaxes_2019(
                    year = 2019, 
                    total = 2984, ),
                var_2020 = rentcast_client.models.property_records_200_response_inner_property_taxes_2020.property_records_200_response_inner_propertyTaxes_2020(
                    year = 2020, 
                    total = 3023, ),
                var_2021 = rentcast_client.models.property_records_200_response_inner_property_taxes_2021.property_records_200_response_inner_propertyTaxes_2021(
                    year = 2021, 
                    total = 3455, ),
                var_2022 = rentcast_client.models.property_records_200_response_inner_property_taxes_2022.property_records_200_response_inner_propertyTaxes_2022(
                    year = 2022, 
                    total = 4091, ),
                var_2023 = rentcast_client.models.property_records_200_response_inner_property_taxes_2023.property_records_200_response_inner_propertyTaxes_2023(
                    year = 2023, 
                    total = 4201, )
            )
        else:
            return RentcastPropertyRecords200ResponseInnerPropertyTaxes(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerPropertyTaxes(self):
        """Test RentcastPropertyRecords200ResponseInnerPropertyTaxes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
