# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_tax_assessments import RentcastPropertyRecords200ResponseInnerTaxAssessments

class TestRentcastPropertyRecords200ResponseInnerTaxAssessments(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerTaxAssessments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerTaxAssessments:
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerTaxAssessments`
        """
        model = RentcastPropertyRecords200ResponseInnerTaxAssessments()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments(
                var_2019 = rentcast_client.models.property_records_200_response_inner_tax_assessments_2019.property_records_200_response_inner_taxAssessments_2019(
                    year = 2019, 
                    value = 135430, 
                    land = 23450, 
                    improvements = 111980, ),
                var_2020 = rentcast_client.models.property_records_200_response_inner_tax_assessments_2020.property_records_200_response_inner_taxAssessments_2020(
                    year = 2020, 
                    value = 142610, 
                    land = 23450, 
                    improvements = 119160, ),
                var_2021 = rentcast_client.models.property_records_200_response_inner_tax_assessments_2021.property_records_200_response_inner_taxAssessments_2021(
                    year = 2021, 
                    value = 163440, 
                    land = 45050, 
                    improvements = 118390, ),
                var_2022 = rentcast_client.models.property_records_200_response_inner_tax_assessments_2022.property_records_200_response_inner_taxAssessments_2022(
                    year = 2022, 
                    value = 197600, 
                    land = 49560, 
                    improvements = 148040, ),
                var_2023 = rentcast_client.models.property_records_200_response_inner_tax_assessments_2023.property_records_200_response_inner_taxAssessments_2023(
                    year = 2023, 
                    value = 225790, 
                    land = 59380, 
                    improvements = 166410, )
            )
        else:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerTaxAssessments(self):
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
