# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_data_by_property_type_inner import RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner(
                property_type = 'Condo',
                average_price = 144900,
                median_price = 144900,
                min_price = 144900,
                max_price = 144900,
                average_price_per_square_foot = 129.26,
                median_price_per_square_foot = 129.26,
                min_price_per_square_foot = 129.26,
                max_price_per_square_foot = 129.26,
                average_square_footage = 1121,
                median_square_footage = 1121,
                min_square_footage = 1121,
                max_square_footage = 1121,
                average_days_on_market = 61,
                median_days_on_market = 61,
                min_days_on_market = 61,
                max_days_on_market = 61,
                new_listings = 0,
                total_listings = 1
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
