# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_rental_listings_long_term200_response_inner_listing_agent import RentcastRentalListingsLongTerm200ResponseInnerListingAgent

class TestRentcastRentalListingsLongTerm200ResponseInnerListingAgent(unittest.TestCase):
    """RentcastRentalListingsLongTerm200ResponseInnerListingAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastRentalListingsLongTerm200ResponseInnerListingAgent:
        """Test RentcastRentalListingsLongTerm200ResponseInnerListingAgent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastRentalListingsLongTerm200ResponseInnerListingAgent`
        """
        model = RentcastRentalListingsLongTerm200ResponseInnerListingAgent()
        if include_optional:
            return RentcastRentalListingsLongTerm200ResponseInnerListingAgent(
                name = 'Zachary Barton',
                phone = '5129948203',
                email = 'zak-barton@realtytexas.com',
                website = 'https://zak-barton.realtytexas.homes'
            )
        else:
            return RentcastRentalListingsLongTerm200ResponseInnerListingAgent(
        )
        """

    def testRentcastRentalListingsLongTerm200ResponseInnerListingAgent(self):
        """Test RentcastRentalListingsLongTerm200ResponseInnerListingAgent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
