# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_history20241118 import RentcastPropertyRecords200ResponseInnerHistory20241118

class TestRentcastPropertyRecords200ResponseInnerHistory20241118(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerHistory20241118 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerHistory20241118:
        """Test RentcastPropertyRecords200ResponseInnerHistory20241118
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerHistory20241118`
        """
        model = RentcastPropertyRecords200ResponseInnerHistory20241118()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerHistory20241118(
                event = 'Sale',
                var_date = '2024-11-18T00:00:00.000Z',
                price = 270000
            )
        else:
            return RentcastPropertyRecords200ResponseInnerHistory20241118(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerHistory20241118(self):
        """Test RentcastPropertyRecords200ResponseInnerHistory20241118"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
