# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202507_data_by_property_type_inner import RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner(
                property_type = 'Condo',
                average_price = 399100,
                median_price = 157500,
                min_price = 124900,
                max_price = 1599000,
                average_price_per_square_foot = 175.02,
                median_price_per_square_foot = 133.66,
                min_price_per_square_foot = 119.07,
                max_price_per_square_foot = 357.48,
                average_square_footage = 1700,
                median_square_footage = 1148,
                min_square_footage = 1049,
                max_square_footage = 4473,
                average_days_on_market = 97.5,
                median_days_on_market = 85,
                min_days_on_market = 7,
                max_days_on_market = 225,
                new_listings = 2,
                total_listings = 6
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507DataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
