# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_data_by_bedrooms_inner import RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner

class TestRentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner:
        """Test RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner`
        """
        model = RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner(
                bedrooms = 1,
                average_rent = 842,
                median_rent = 850,
                min_rent = 750,
                max_rent = 945,
                average_rent_per_square_foot = 1.35,
                median_rent_per_square_foot = 1.3,
                min_rent_per_square_foot = 1.06,
                max_rent_per_square_foot = 1.57,
                average_square_footage = 679,
                median_square_footage = 650,
                min_square_footage = 590,
                max_square_footage = 800,
                average_days_on_market = 27.33,
                median_days_on_market = 9,
                min_days_on_market = 1,
                max_days_on_market = 80,
                new_listings = 1,
                total_listings = 7
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner(self):
        """Test RentcastMarketStatistics200ResponseRentalDataDataByBedroomsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
