# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_tax_assessments2021 import RentcastPropertyRecords200ResponseInnerTaxAssessments2021

class TestRentcastPropertyRecords200ResponseInnerTaxAssessments2021(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerTaxAssessments2021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerTaxAssessments2021:
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments2021
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerTaxAssessments2021`
        """
        model = RentcastPropertyRecords200ResponseInnerTaxAssessments2021()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments2021(
                year = 2021,
                value = 163440,
                land = 45050,
                improvements = 118390
            )
        else:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments2021(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerTaxAssessments2021(self):
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments2021"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
