# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_sale_listings200_response_inner_listing_agent import RentcastSaleListings200ResponseInnerListingAgent

class TestRentcastSaleListings200ResponseInnerListingAgent(unittest.TestCase):
    """RentcastSaleListings200ResponseInnerListingAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastSaleListings200ResponseInnerListingAgent:
        """Test RentcastSaleListings200ResponseInnerListingAgent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastSaleListings200ResponseInnerListingAgent`
        """
        model = RentcastSaleListings200ResponseInnerListingAgent()
        if include_optional:
            return RentcastSaleListings200ResponseInnerListingAgent(
                name = 'Jennifer Welch',
                phone = '5124313110',
                email = 'jennifer@gottesmanresidential.com',
                website = 'https://www.gottesmanresidential.com'
            )
        else:
            return RentcastSaleListings200ResponseInnerListingAgent(
        )
        """

    def testRentcastSaleListings200ResponseInnerListingAgent(self):
        """Test RentcastSaleListings200ResponseInnerListingAgent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
