# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_history202409_data_by_property_type_inner import RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner(
                property_type = 'Apartment',
                average_rent = 1148,
                median_rent = 975,
                min_rent = 750,
                max_rent = 1975,
                average_rent_per_square_foot = 1.25,
                median_rent_per_square_foot = 1.07,
                min_rent_per_square_foot = 1.03,
                max_rent_per_square_foot = 1.59,
                average_square_footage = 949,
                median_square_footage = 850,
                min_square_footage = 650,
                max_square_footage = 1560,
                average_days_on_market = 18.69,
                median_days_on_market = 17,
                min_days_on_market = 1,
                max_days_on_market = 80,
                new_listings = 7,
                total_listings = 14
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202409DataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
