# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_history202508 import RentcastMarketStatistics200ResponseRentalDataHistory202508

class TestRentcastMarketStatistics200ResponseRentalDataHistory202508(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataHistory202508 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataHistory202508:
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202508
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataHistory202508`
        """
        model = RentcastMarketStatistics200ResponseRentalDataHistory202508()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataHistory202508(
                var_date = '2025-08-01T00:00:00.000Z',
                average_rent = 1491,
                median_rent = 1400,
                min_rent = 400,
                max_rent = 3750,
                average_rent_per_square_foot = 1.36,
                median_rent_per_square_foot = 1.29,
                min_rent_per_square_foot = 0.88,
                max_rent_per_square_foot = 2.38,
                average_square_footage = 1144,
                median_square_footage = 1024,
                min_square_footage = 590,
                max_square_footage = 2562,
                average_days_on_market = 37.82,
                median_days_on_market = 1,
                min_days_on_market = 1,
                max_days_on_market = 322,
                new_listings = 39,
                total_listings = 94,
                data_by_property_type = [
                    rentcast_client.models.market_statistics_200_response_rental_data_history_2025_08_data_by_property_type_inner.market_statistics_200_response_rentalData_history_2025_08_dataByPropertyType_inner(
                        property_type = 'Apartment', 
                        average_rent = 1139, 
                        median_rent = 1025, 
                        min_rent = 875, 
                        max_rent = 1815, 
                        average_rent_per_square_foot = 1.36, 
                        median_rent_per_square_foot = 1.24, 
                        min_rent_per_square_foot = 0.88, 
                        max_rent_per_square_foot = 2.01, 
                        average_square_footage = 875, 
                        median_square_footage = 950, 
                        min_square_footage = 629, 
                        max_square_footage = 1192, 
                        average_days_on_market = 66.26, 
                        median_days_on_market = 1, 
                        min_days_on_market = 1, 
                        max_days_on_market = 236, 
                        new_listings = 8, 
                        total_listings = 26, )
                    ],
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_rental_data_data_by_bedrooms_inner.market_statistics_200_response_rentalData_dataByBedrooms_inner(
                        bedrooms = 1, 
                        average_rent = 1043, 
                        median_rent = 945, 
                        min_rent = 400, 
                        max_rent = 1815, 
                        average_rent_per_square_foot = 1.59, 
                        median_rent_per_square_foot = 1.53, 
                        min_rent_per_square_foot = 1.24, 
                        max_rent_per_square_foot = 2.01, 
                        average_square_footage = 735, 
                        median_square_footage = 650, 
                        min_square_footage = 590, 
                        max_square_footage = 1004, 
                        average_days_on_market = 154.08, 
                        median_days_on_market = 147, 
                        min_days_on_market = 1, 
                        max_days_on_market = 322, 
                        new_listings = 1, 
                        total_listings = 14, )
                    ]
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataHistory202508(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataHistory202508(self):
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202508"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
