# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_rental_listings_long_term200_response_inner_history import RentcastRentalListingsLongTerm200ResponseInnerHistory

class TestRentcastRentalListingsLongTerm200ResponseInnerHistory(unittest.TestCase):
    """RentcastRentalListingsLongTerm200ResponseInnerHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastRentalListingsLongTerm200ResponseInnerHistory:
        """Test RentcastRentalListingsLongTerm200ResponseInnerHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastRentalListingsLongTerm200ResponseInnerHistory`
        """
        model = RentcastRentalListingsLongTerm200ResponseInnerHistory()
        if include_optional:
            return RentcastRentalListingsLongTerm200ResponseInnerHistory(
                var_2024_09_18 = rentcast_client.models.rental_listings_long_term_200_response_inner_history_2024_09_18.rental_listings_long_term_200_response_inner_history_2024_09_18(
                    event = 'Rental Listing', 
                    price = 2200, 
                    listing_type = 'Standard', 
                    listed_date = '2024-09-18T00:00:00.000Z', 
                    removed_date = null, 
                    days_on_market = 13, )
            )
        else:
            return RentcastRentalListingsLongTerm200ResponseInnerHistory(
        )
        """

    def testRentcastRentalListingsLongTerm200ResponseInnerHistory(self):
        """Test RentcastRentalListingsLongTerm200ResponseInnerHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
