# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_rental_listings_long_term200_response_inner_listing_office import RentcastRentalListingsLongTerm200ResponseInnerListingOffice

class TestRentcastRentalListingsLongTerm200ResponseInnerListingOffice(unittest.TestCase):
    """RentcastRentalListingsLongTerm200ResponseInnerListingOffice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastRentalListingsLongTerm200ResponseInnerListingOffice:
        """Test RentcastRentalListingsLongTerm200ResponseInnerListingOffice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastRentalListingsLongTerm200ResponseInnerListingOffice`
        """
        model = RentcastRentalListingsLongTerm200ResponseInnerListingOffice()
        if include_optional:
            return RentcastRentalListingsLongTerm200ResponseInnerListingOffice(
                name = 'Realty Texas',
                phone = '5124765348',
                email = 'sales@realtytexas.com',
                website = 'https://www.realtytexas.com'
            )
        else:
            return RentcastRentalListingsLongTerm200ResponseInnerListingOffice(
        )
        """

    def testRentcastRentalListingsLongTerm200ResponseInnerListingOffice(self):
        """Test RentcastRentalListingsLongTerm200ResponseInnerListingOffice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
