# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202508 import RentcastMarketStatistics200ResponseSaleDataHistory202508

class TestRentcastMarketStatistics200ResponseSaleDataHistory202508(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202508 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202508:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202508
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202508`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202508()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202508(
                var_date = '2025-08-01T00:00:00.000Z',
                average_price = 356598,
                median_price = 295000,
                min_price = 8899,
                max_price = 2530000,
                average_price_per_square_foot = 203.45,
                median_price_per_square_foot = 188.61,
                min_price_per_square_foot = 54,
                max_price_per_square_foot = 943.24,
                average_square_footage = 1717,
                median_square_footage = 1573,
                min_square_footage = 636,
                max_square_footage = 6000,
                average_days_on_market = 77,
                median_days_on_market = 61,
                min_days_on_market = 2,
                max_days_on_market = 279,
                new_listings = 41,
                total_listings = 248,
                data_by_property_type = [
                    rentcast_client.models.market_statistics_200_response_sale_data_data_by_property_type_inner.market_statistics_200_response_saleData_dataByPropertyType_inner(
                        property_type = 'Condo', 
                        average_price = 398267, 
                        median_price = 157500, 
                        min_price = 124900, 
                        max_price = 1599000, 
                        average_price_per_square_foot = 174.28, 
                        median_price_per_square_foot = 132.02, 
                        min_price_per_square_foot = 119.07, 
                        max_price_per_square_foot = 357.48, 
                        average_square_footage = 1700, 
                        median_square_footage = 1148, 
                        min_square_footage = 1049, 
                        max_square_footage = 4473, 
                        average_days_on_market = 119.17, 
                        median_days_on_market = 111, 
                        min_days_on_market = 33, 
                        max_days_on_market = 225, 
                        new_listings = 0, 
                        total_listings = 6, )
                    ],
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_sale_data_data_by_bedrooms_inner.market_statistics_200_response_saleData_dataByBedrooms_inner(
                        bedrooms = 0, 
                        average_price = 499900, 
                        median_price = 499900, 
                        min_price = 499900, 
                        max_price = 499900, 
                        average_price_per_square_foot = 83.32, 
                        median_price_per_square_foot = 83.32, 
                        min_price_per_square_foot = 83.32, 
                        max_price_per_square_foot = 83.32, 
                        average_square_footage = 6000, 
                        median_square_footage = 6000, 
                        min_square_footage = 6000, 
                        max_square_footage = 6000, 
                        average_days_on_market = 81, 
                        median_days_on_market = 81, 
                        min_days_on_market = 81, 
                        max_days_on_market = 81, 
                        new_listings = 0, 
                        total_listings = 1, )
                    ]
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202508(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202508(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202508"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
