# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_history20040616 import RentcastPropertyRecords200ResponseInnerHistory20040616

class TestRentcastPropertyRecords200ResponseInnerHistory20040616(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerHistory20040616 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerHistory20040616:
        """Test RentcastPropertyRecords200ResponseInnerHistory20040616
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerHistory20040616`
        """
        model = RentcastPropertyRecords200ResponseInnerHistory20040616()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerHistory20040616(
                event = 'Sale',
                var_date = '2004-06-16T00:00:00.000Z',
                price = 95000
            )
        else:
            return RentcastPropertyRecords200ResponseInnerHistory20040616(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerHistory20040616(self):
        """Test RentcastPropertyRecords200ResponseInnerHistory20040616"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
