# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_history202408_data_by_bedrooms_inner import RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner

class TestRentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner:
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner`
        """
        model = RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner(
                bedrooms = 1,
                average_rent = 953,
                median_rent = 825,
                min_rent = 750,
                max_rent = 1610,
                average_rent_per_square_foot = 1.41,
                median_rent_per_square_foot = 1.3,
                min_rent_per_square_foot = 1.06,
                max_rent_per_square_foot = 2.16,
                average_square_footage = 732,
                median_square_footage = 675,
                min_square_footage = 650,
                max_square_footage = 950,
                average_days_on_market = 33.44,
                median_days_on_market = 17,
                min_days_on_market = 1,
                max_days_on_market = 124,
                new_listings = 3,
                total_listings = 10
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner(self):
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202408DataByBedroomsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
