# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202409_data_by_property_type_inner import RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner(
                property_type = 'Condo',
                average_price = 149900,
                median_price = 149900,
                min_price = 149900,
                max_price = 149900,
                average_price_per_square_foot = 133.72,
                median_price_per_square_foot = 133.72,
                min_price_per_square_foot = 133.72,
                max_price_per_square_foot = 133.72,
                average_square_footage = 1121,
                median_square_footage = 1121,
                min_square_footage = 1121,
                max_square_footage = 1121,
                average_days_on_market = 47,
                median_days_on_market = 47,
                min_days_on_market = 47,
                max_days_on_market = 47,
                new_listings = 0,
                total_listings = 1
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202409DataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
