# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_history202506 import RentcastMarketStatistics200ResponseRentalDataHistory202506

class TestRentcastMarketStatistics200ResponseRentalDataHistory202506(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataHistory202506 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataHistory202506:
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202506
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataHistory202506`
        """
        model = RentcastMarketStatistics200ResponseRentalDataHistory202506()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataHistory202506(
                var_date = '2025-06-01T00:00:00.000Z',
                average_rent = 1555,
                median_rent = 1495,
                min_rent = 400,
                max_rent = 3200,
                average_rent_per_square_foot = 1.33,
                median_rent_per_square_foot = 1.29,
                min_rent_per_square_foot = 0.81,
                max_rent_per_square_foot = 2.04,
                average_square_footage = 1269,
                median_square_footage = 1100,
                min_square_footage = 590,
                max_square_footage = 2802,
                average_days_on_market = 18.04,
                median_days_on_market = 1,
                min_days_on_market = 1,
                max_days_on_market = 257,
                new_listings = 50,
                total_listings = 84,
                data_by_property_type = [
                    rentcast_client.models.market_statistics_200_response_rental_data_history_2025_06_data_by_property_type_inner.market_statistics_200_response_rentalData_history_2025_06_dataByPropertyType_inner(
                        property_type = 'Apartment', 
                        average_rent = 1086, 
                        median_rent = 1050, 
                        min_rent = 945, 
                        max_rent = 1395, 
                        average_rent_per_square_foot = 1.2, 
                        median_rent_per_square_foot = 1.07, 
                        min_rent_per_square_foot = 1.05, 
                        max_rent_per_square_foot = 1.47, 
                        average_square_footage = 883, 
                        median_square_footage = 950, 
                        min_square_footage = 650, 
                        max_square_footage = 1020, 
                        average_days_on_market = 1, 
                        median_days_on_market = 1, 
                        min_days_on_market = 1, 
                        max_days_on_market = 1, 
                        new_listings = 6, 
                        total_listings = 7, )
                    ],
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_rental_data_history_2025_06_data_by_bedrooms_inner.market_statistics_200_response_rentalData_history_2025_06_dataByBedrooms_inner(
                        bedrooms = 1, 
                        average_rent = 852, 
                        median_rent = 930, 
                        min_rent = 400, 
                        max_rent = 1100, 
                        average_rent_per_square_foot = 1.35, 
                        median_rent_per_square_foot = 1.34, 
                        min_rent_per_square_foot = 1, 
                        max_rent_per_square_foot = 1.6, 
                        average_square_footage = 673, 
                        median_square_footage = 650, 
                        min_square_footage = 590, 
                        max_square_footage = 800, 
                        average_days_on_market = 47.4, 
                        median_days_on_market = 1, 
                        min_days_on_market = 1, 
                        max_days_on_market = 257, 
                        new_listings = 5, 
                        total_listings = 11, )
                    ]
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataHistory202506(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataHistory202506(self):
        """Test RentcastMarketStatistics200ResponseRentalDataHistory202506"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
