# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202507 import RentcastMarketStatistics200ResponseSaleDataHistory202507

class TestRentcastMarketStatistics200ResponseSaleDataHistory202507(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202507 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202507:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202507`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202507()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507(
                var_date = '2025-07-01T00:00:00.000Z',
                average_price = 355280,
                median_price = 290000,
                min_price = 8899,
                max_price = 2530000,
                average_price_per_square_foot = 205.14,
                median_price_per_square_foot = 191.71,
                min_price_per_square_foot = 54,
                max_price_per_square_foot = 962.5,
                average_square_footage = 1702,
                median_square_footage = 1560,
                min_square_footage = 800,
                max_square_footage = 6000,
                average_days_on_market = 76.27,
                median_days_on_market = 61,
                min_days_on_market = 2,
                max_days_on_market = 351,
                new_listings = 55,
                total_listings = 244,
                data_by_property_type = [
                    rentcast_client.models.market_statistics_200_response_sale_data_history_2025_07_data_by_property_type_inner.market_statistics_200_response_saleData_history_2025_07_dataByPropertyType_inner(
                        property_type = 'Condo', 
                        average_price = 399100, 
                        median_price = 157500, 
                        min_price = 124900, 
                        max_price = 1599000, 
                        average_price_per_square_foot = 175.02, 
                        median_price_per_square_foot = 133.66, 
                        min_price_per_square_foot = 119.07, 
                        max_price_per_square_foot = 357.48, 
                        average_square_footage = 1700, 
                        median_square_footage = 1148, 
                        min_square_footage = 1049, 
                        max_square_footage = 4473, 
                        average_days_on_market = 97.5, 
                        median_days_on_market = 85, 
                        min_days_on_market = 7, 
                        max_days_on_market = 225, 
                        new_listings = 2, 
                        total_listings = 6, )
                    ],
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_sale_data_history_2025_07_data_by_bedrooms_inner.market_statistics_200_response_saleData_history_2025_07_dataByBedrooms_inner(
                        bedrooms = 0, 
                        average_price = 499900, 
                        median_price = 499900, 
                        min_price = 499900, 
                        max_price = 499900, 
                        average_price_per_square_foot = 83.32, 
                        median_price_per_square_foot = 83.32, 
                        min_price_per_square_foot = 83.32, 
                        max_price_per_square_foot = 83.32, 
                        average_square_footage = 6000, 
                        median_square_footage = 6000, 
                        min_square_footage = 6000, 
                        max_square_footage = 6000, 
                        average_days_on_market = 55, 
                        median_days_on_market = 55, 
                        min_days_on_market = 55, 
                        max_days_on_market = 55, 
                        new_listings = 0, 
                        total_listings = 1, )
                    ]
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202507(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
