# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202506_data_by_property_type_inner import RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner(
                property_type = 'Condo',
                average_price = 380983,
                median_price = 125000,
                min_price = 105000,
                max_price = 1599000,
                average_price_per_square_foot = 166.94,
                median_price_per_square_foot = 129.63,
                min_price_per_square_foot = 119.07,
                max_price_per_square_foot = 357.48,
                average_square_footage = 1630,
                median_square_footage = 1049,
                min_square_footage = 810,
                max_square_footage = 4473,
                average_days_on_market = 92.83,
                median_days_on_market = 54,
                min_days_on_market = 53,
                max_days_on_market = 220,
                new_listings = 0,
                total_listings = 6
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
