# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records401_response import RentcastPropertyRecords401Response

class TestRentcastPropertyRecords401Response(unittest.TestCase):
    """RentcastPropertyRecords401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords401Response:
        """Test RentcastPropertyRecords401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords401Response`
        """
        model = RentcastPropertyRecords401Response()
        if include_optional:
            return RentcastPropertyRecords401Response(
                status = 1.337,
                error = '',
                message = ''
            )
        else:
            return RentcastPropertyRecords401Response(
        )
        """

    def testRentcastPropertyRecords401Response(self):
        """Test RentcastPropertyRecords401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
