# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202408_data_by_property_type_inner import RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner(
                property_type = 'Condo',
                average_price = 175445,
                median_price = 154500,
                min_price = 154500,
                max_price = 196390,
                average_price_per_square_foot = None,
                median_price_per_square_foot = None,
                min_price_per_square_foot = None,
                max_price_per_square_foot = None,
                average_square_footage = None,
                median_square_footage = None,
                min_square_footage = None,
                max_square_footage = None,
                average_days_on_market = 124,
                median_days_on_market = 18,
                min_days_on_market = 18,
                max_days_on_market = 230,
                new_listings = 1,
                total_listings = 2
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
