# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_tax_assessments2020 import RentcastPropertyRecords200ResponseInnerTaxAssessments2020

class TestRentcastPropertyRecords200ResponseInnerTaxAssessments2020(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerTaxAssessments2020 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerTaxAssessments2020:
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments2020
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerTaxAssessments2020`
        """
        model = RentcastPropertyRecords200ResponseInnerTaxAssessments2020()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments2020(
                year = 2020,
                value = 142610,
                land = 23450,
                improvements = 119160
            )
        else:
            return RentcastPropertyRecords200ResponseInnerTaxAssessments2020(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerTaxAssessments2020(self):
        """Test RentcastPropertyRecords200ResponseInnerTaxAssessments2020"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
