# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202507_data_by_bedrooms_inner import RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner

class TestRentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner(
                bedrooms = 0,
                average_price = 499900,
                median_price = 499900,
                min_price = 499900,
                max_price = 499900,
                average_price_per_square_foot = 83.32,
                median_price_per_square_foot = 83.32,
                min_price_per_square_foot = 83.32,
                max_price_per_square_foot = 83.32,
                average_square_footage = 6000,
                median_square_footage = 6000,
                min_square_footage = 6000,
                max_square_footage = 6000,
                average_days_on_market = 55,
                median_days_on_market = 55,
                min_days_on_market = 55,
                max_days_on_market = 55,
                new_listings = 0,
                total_listings = 1
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202507DataByBedroomsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
