# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_data_by_bedrooms_inner import RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner

class TestRentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner:
        """Test RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner`
        """
        model = RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner(
                bedrooms = 1,
                average_price = 186725,
                median_price = 153000,
                min_price = 147900,
                max_price = 237000,
                average_price_per_square_foot = 240.84,
                median_price_per_square_foot = 191.01,
                min_price_per_square_foot = 184.88,
                max_price_per_square_foot = 342.62,
                average_square_footage = 795,
                median_square_footage = 800,
                min_square_footage = 610,
                max_square_footage = 968,
                average_days_on_market = 123,
                median_days_on_market = 56,
                min_days_on_market = 20,
                max_days_on_market = 314,
                new_listings = 0,
                total_listings = 4
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner(self):
        """Test RentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
