# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_hoa import RentcastPropertyRecords200ResponseInnerHoa

class TestRentcastPropertyRecords200ResponseInnerHoa(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerHoa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerHoa:
        """Test RentcastPropertyRecords200ResponseInnerHoa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerHoa`
        """
        model = RentcastPropertyRecords200ResponseInnerHoa()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerHoa(
                fee = 175
            )
        else:
            return RentcastPropertyRecords200ResponseInnerHoa(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerHoa(self):
        """Test RentcastPropertyRecords200ResponseInnerHoa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
