# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_sale_data_history202408 import RentcastMarketStatistics200ResponseSaleDataHistory202408

class TestRentcastMarketStatistics200ResponseSaleDataHistory202408(unittest.TestCase):
    """RentcastMarketStatistics200ResponseSaleDataHistory202408 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseSaleDataHistory202408:
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202408
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseSaleDataHistory202408`
        """
        model = RentcastMarketStatistics200ResponseSaleDataHistory202408()
        if include_optional:
            return RentcastMarketStatistics200ResponseSaleDataHistory202408(
                var_date = '2024-08-01T00:00:00.000Z',
                average_price = 304256,
                median_price = 284900,
                min_price = 75000,
                max_price = 975000,
                average_price_per_square_foot = 177.79,
                median_price_per_square_foot = 174.82,
                min_price_per_square_foot = 115.81,
                max_price_per_square_foot = 342.62,
                average_square_footage = 1759,
                median_square_footage = 1591,
                min_square_footage = 610,
                max_square_footage = 4588,
                average_days_on_market = 56.94,
                median_days_on_market = 41,
                min_days_on_market = 2,
                max_days_on_market = 327,
                new_listings = 56,
                total_listings = 215,
                data_by_property_type = [
                    rentcast_client.models.market_statistics_200_response_sale_data_history_2024_08_data_by_property_type_inner.market_statistics_200_response_saleData_history_2024_08_dataByPropertyType_inner(
                        property_type = 'Condo', 
                        average_price = 175445, 
                        median_price = 154500, 
                        min_price = 154500, 
                        max_price = 196390, 
                        average_price_per_square_foot = null, 
                        median_price_per_square_foot = null, 
                        min_price_per_square_foot = null, 
                        max_price_per_square_foot = null, 
                        average_square_footage = null, 
                        median_square_footage = null, 
                        min_square_footage = null, 
                        max_square_footage = null, 
                        average_days_on_market = 124, 
                        median_days_on_market = 18, 
                        min_days_on_market = 18, 
                        max_days_on_market = 230, 
                        new_listings = 1, 
                        total_listings = 2, )
                    ],
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_sale_data_history_2024_08_data_by_bedrooms_inner.market_statistics_200_response_saleData_history_2024_08_dataByBedrooms_inner(
                        bedrooms = 1, 
                        average_price = 197967, 
                        median_price = 209000, 
                        min_price = 147900, 
                        max_price = 237000, 
                        average_price_per_square_foot = 342.62, 
                        median_price_per_square_foot = 342.62, 
                        min_price_per_square_foot = 342.62, 
                        max_price_per_square_foot = 342.62, 
                        average_square_footage = 610, 
                        median_square_footage = 610, 
                        min_square_footage = 610, 
                        max_square_footage = 610, 
                        average_days_on_market = 132, 
                        median_days_on_market = 69, 
                        min_days_on_market = 56, 
                        max_days_on_market = 271, 
                        new_listings = 0, 
                        total_listings = 3, )
                    ]
            )
        else:
            return RentcastMarketStatistics200ResponseSaleDataHistory202408(
        )
        """

    def testRentcastMarketStatistics200ResponseSaleDataHistory202408(self):
        """Test RentcastMarketStatistics200ResponseSaleDataHistory202408"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
