# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_market_statistics200_response_rental_data_data_by_property_type_inner import RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner

class TestRentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner(unittest.TestCase):
    """RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner:
        """Test RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner`
        """
        model = RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner()
        if include_optional:
            return RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner(
                property_type = 'Apartment',
                average_rent = 1148,
                median_rent = 1050,
                min_rent = 750,
                max_rent = 1975,
                average_rent_per_square_foot = 1.23,
                median_rent_per_square_foot = 1.13,
                min_rent_per_square_foot = 1.03,
                max_rent_per_square_foot = 1.59,
                average_square_footage = 957,
                median_square_footage = 950,
                min_square_footage = 650,
                max_square_footage = 1560,
                average_days_on_market = 17.43,
                median_days_on_market = 1,
                min_days_on_market = 1,
                max_days_on_market = 80,
                new_listings = 5,
                total_listings = 15
            )
        else:
            return RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner(
        )
        """

    def testRentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner(self):
        """Test RentcastMarketStatistics200ResponseRentalDataDataByPropertyTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
