# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.rentcast_property_records200_response_inner_property_taxes2024 import RentcastPropertyRecords200ResponseInnerPropertyTaxes2024

class TestRentcastPropertyRecords200ResponseInnerPropertyTaxes2024(unittest.TestCase):
    """RentcastPropertyRecords200ResponseInnerPropertyTaxes2024 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RentcastPropertyRecords200ResponseInnerPropertyTaxes2024:
        """Test RentcastPropertyRecords200ResponseInnerPropertyTaxes2024
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RentcastPropertyRecords200ResponseInnerPropertyTaxes2024`
        """
        model = RentcastPropertyRecords200ResponseInnerPropertyTaxes2024()
        if include_optional:
            return RentcastPropertyRecords200ResponseInnerPropertyTaxes2024(
                year = 2024,
                total = 4065
            )
        else:
            return RentcastPropertyRecords200ResponseInnerPropertyTaxes2024(
        )
        """

    def testRentcastPropertyRecords200ResponseInnerPropertyTaxes2024(self):
        """Test RentcastPropertyRecords200ResponseInnerPropertyTaxes2024"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
