# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner(BaseModel):
    """
    RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner
    """ # noqa: E501
    property_type: Optional[StrictStr] = Field(default=None, alias="propertyType")
    average_price: Optional[StrictInt] = Field(default=0, alias="averagePrice")
    median_price: Optional[StrictInt] = Field(default=0, alias="medianPrice")
    min_price: Optional[StrictInt] = Field(default=0, alias="minPrice")
    max_price: Optional[StrictInt] = Field(default=0, alias="maxPrice")
    average_price_per_square_foot: Optional[Any] = Field(default=None, alias="averagePricePerSquareFoot")
    median_price_per_square_foot: Optional[Any] = Field(default=None, alias="medianPricePerSquareFoot")
    min_price_per_square_foot: Optional[Any] = Field(default=None, alias="minPricePerSquareFoot")
    max_price_per_square_foot: Optional[Any] = Field(default=None, alias="maxPricePerSquareFoot")
    average_square_footage: Optional[Any] = Field(default=None, alias="averageSquareFootage")
    median_square_footage: Optional[Any] = Field(default=None, alias="medianSquareFootage")
    min_square_footage: Optional[Any] = Field(default=None, alias="minSquareFootage")
    max_square_footage: Optional[Any] = Field(default=None, alias="maxSquareFootage")
    average_days_on_market: Optional[StrictInt] = Field(default=0, alias="averageDaysOnMarket")
    median_days_on_market: Optional[StrictInt] = Field(default=0, alias="medianDaysOnMarket")
    min_days_on_market: Optional[StrictInt] = Field(default=0, alias="minDaysOnMarket")
    max_days_on_market: Optional[StrictInt] = Field(default=0, alias="maxDaysOnMarket")
    new_listings: Optional[StrictInt] = Field(default=0, alias="newListings")
    total_listings: Optional[StrictInt] = Field(default=0, alias="totalListings")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["propertyType", "averagePrice", "medianPrice", "minPrice", "maxPrice", "averagePricePerSquareFoot", "medianPricePerSquareFoot", "minPricePerSquareFoot", "maxPricePerSquareFoot", "averageSquareFootage", "medianSquareFootage", "minSquareFootage", "maxSquareFootage", "averageDaysOnMarket", "medianDaysOnMarket", "minDaysOnMarket", "maxDaysOnMarket", "newListings", "totalListings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if average_price_per_square_foot (nullable) is None
        # and model_fields_set contains the field
        if self.average_price_per_square_foot is None and "average_price_per_square_foot" in self.model_fields_set:
            _dict['averagePricePerSquareFoot'] = None

        # set to None if median_price_per_square_foot (nullable) is None
        # and model_fields_set contains the field
        if self.median_price_per_square_foot is None and "median_price_per_square_foot" in self.model_fields_set:
            _dict['medianPricePerSquareFoot'] = None

        # set to None if min_price_per_square_foot (nullable) is None
        # and model_fields_set contains the field
        if self.min_price_per_square_foot is None and "min_price_per_square_foot" in self.model_fields_set:
            _dict['minPricePerSquareFoot'] = None

        # set to None if max_price_per_square_foot (nullable) is None
        # and model_fields_set contains the field
        if self.max_price_per_square_foot is None and "max_price_per_square_foot" in self.model_fields_set:
            _dict['maxPricePerSquareFoot'] = None

        # set to None if average_square_footage (nullable) is None
        # and model_fields_set contains the field
        if self.average_square_footage is None and "average_square_footage" in self.model_fields_set:
            _dict['averageSquareFootage'] = None

        # set to None if median_square_footage (nullable) is None
        # and model_fields_set contains the field
        if self.median_square_footage is None and "median_square_footage" in self.model_fields_set:
            _dict['medianSquareFootage'] = None

        # set to None if min_square_footage (nullable) is None
        # and model_fields_set contains the field
        if self.min_square_footage is None and "min_square_footage" in self.model_fields_set:
            _dict['minSquareFootage'] = None

        # set to None if max_square_footage (nullable) is None
        # and model_fields_set contains the field
        if self.max_square_footage is None and "max_square_footage" in self.model_fields_set:
            _dict['maxSquareFootage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202408DataByPropertyTypeInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "propertyType": obj.get("propertyType"),
            "averagePrice": obj.get("averagePrice") if obj.get("averagePrice") is not None else 0,
            "medianPrice": obj.get("medianPrice") if obj.get("medianPrice") is not None else 0,
            "minPrice": obj.get("minPrice") if obj.get("minPrice") is not None else 0,
            "maxPrice": obj.get("maxPrice") if obj.get("maxPrice") is not None else 0,
            "averagePricePerSquareFoot": obj.get("averagePricePerSquareFoot"),
            "medianPricePerSquareFoot": obj.get("medianPricePerSquareFoot"),
            "minPricePerSquareFoot": obj.get("minPricePerSquareFoot"),
            "maxPricePerSquareFoot": obj.get("maxPricePerSquareFoot"),
            "averageSquareFootage": obj.get("averageSquareFootage"),
            "medianSquareFootage": obj.get("medianSquareFootage"),
            "minSquareFootage": obj.get("minSquareFootage"),
            "maxSquareFootage": obj.get("maxSquareFootage"),
            "averageDaysOnMarket": obj.get("averageDaysOnMarket") if obj.get("averageDaysOnMarket") is not None else 0,
            "medianDaysOnMarket": obj.get("medianDaysOnMarket") if obj.get("medianDaysOnMarket") is not None else 0,
            "minDaysOnMarket": obj.get("minDaysOnMarket") if obj.get("minDaysOnMarket") is not None else 0,
            "maxDaysOnMarket": obj.get("maxDaysOnMarket") if obj.get("maxDaysOnMarket") is not None else 0,
            "newListings": obj.get("newListings") if obj.get("newListings") is not None else 0,
            "totalListings": obj.get("totalListings") if obj.get("totalListings") is not None else 0
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


