# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RentcastMarketStatistics200ResponseSaleDataHistory202410(BaseModel):
    """
    RentcastMarketStatistics200ResponseSaleDataHistory202410
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    average_price: Optional[StrictInt] = Field(default=0, alias="averagePrice")
    median_price: Optional[StrictInt] = Field(default=0, alias="medianPrice")
    min_price: Optional[StrictInt] = Field(default=0, alias="minPrice")
    max_price: Optional[StrictInt] = Field(default=0, alias="maxPrice")
    average_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="averagePricePerSquareFoot")
    median_price_per_square_foot: Optional[StrictInt] = Field(default=0, alias="medianPricePerSquareFoot")
    min_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="minPricePerSquareFoot")
    max_price_per_square_foot: Optional[StrictInt] = Field(default=0, alias="maxPricePerSquareFoot")
    average_square_footage: Optional[StrictInt] = Field(default=0, alias="averageSquareFootage")
    median_square_footage: Optional[StrictInt] = Field(default=0, alias="medianSquareFootage")
    min_square_footage: Optional[StrictInt] = Field(default=0, alias="minSquareFootage")
    max_square_footage: Optional[StrictInt] = Field(default=0, alias="maxSquareFootage")
    average_days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="averageDaysOnMarket")
    median_days_on_market: Optional[StrictInt] = Field(default=0, alias="medianDaysOnMarket")
    min_days_on_market: Optional[StrictInt] = Field(default=0, alias="minDaysOnMarket")
    max_days_on_market: Optional[StrictInt] = Field(default=0, alias="maxDaysOnMarket")
    new_listings: Optional[StrictInt] = Field(default=0, alias="newListings")
    total_listings: Optional[StrictInt] = Field(default=0, alias="totalListings")
    data_by_property_type: Optional[List[RentcastRentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner]] = Field(default=None, alias="dataByPropertyType")
    data_by_bedrooms: Optional[List[RentcastRentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner]] = Field(default=None, alias="dataByBedrooms")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["date", "averagePrice", "medianPrice", "minPrice", "maxPrice", "averagePricePerSquareFoot", "medianPricePerSquareFoot", "minPricePerSquareFoot", "maxPricePerSquareFoot", "averageSquareFootage", "medianSquareFootage", "minSquareFootage", "maxSquareFootage", "averageDaysOnMarket", "medianDaysOnMarket", "minDaysOnMarket", "maxDaysOnMarket", "newListings", "totalListings", "dataByPropertyType", "dataByBedrooms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202410 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_by_property_type (list)
        _items = []
        if self.data_by_property_type:
            for _item_data_by_property_type in self.data_by_property_type:
                if _item_data_by_property_type:
                    _items.append(_item_data_by_property_type.to_dict())
            _dict['dataByPropertyType'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data_by_bedrooms (list)
        _items = []
        if self.data_by_bedrooms:
            for _item_data_by_bedrooms in self.data_by_bedrooms:
                if _item_data_by_bedrooms:
                    _items.append(_item_data_by_bedrooms.to_dict())
            _dict['dataByBedrooms'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202410 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "averagePrice": obj.get("averagePrice") if obj.get("averagePrice") is not None else 0,
            "medianPrice": obj.get("medianPrice") if obj.get("medianPrice") is not None else 0,
            "minPrice": obj.get("minPrice") if obj.get("minPrice") is not None else 0,
            "maxPrice": obj.get("maxPrice") if obj.get("maxPrice") is not None else 0,
            "averagePricePerSquareFoot": obj.get("averagePricePerSquareFoot") if obj.get("averagePricePerSquareFoot") is not None else 0,
            "medianPricePerSquareFoot": obj.get("medianPricePerSquareFoot") if obj.get("medianPricePerSquareFoot") is not None else 0,
            "minPricePerSquareFoot": obj.get("minPricePerSquareFoot") if obj.get("minPricePerSquareFoot") is not None else 0,
            "maxPricePerSquareFoot": obj.get("maxPricePerSquareFoot") if obj.get("maxPricePerSquareFoot") is not None else 0,
            "averageSquareFootage": obj.get("averageSquareFootage") if obj.get("averageSquareFootage") is not None else 0,
            "medianSquareFootage": obj.get("medianSquareFootage") if obj.get("medianSquareFootage") is not None else 0,
            "minSquareFootage": obj.get("minSquareFootage") if obj.get("minSquareFootage") is not None else 0,
            "maxSquareFootage": obj.get("maxSquareFootage") if obj.get("maxSquareFootage") is not None else 0,
            "averageDaysOnMarket": obj.get("averageDaysOnMarket") if obj.get("averageDaysOnMarket") is not None else 0,
            "medianDaysOnMarket": obj.get("medianDaysOnMarket") if obj.get("medianDaysOnMarket") is not None else 0,
            "minDaysOnMarket": obj.get("minDaysOnMarket") if obj.get("minDaysOnMarket") is not None else 0,
            "maxDaysOnMarket": obj.get("maxDaysOnMarket") if obj.get("maxDaysOnMarket") is not None else 0,
            "newListings": obj.get("newListings") if obj.get("newListings") is not None else 0,
            "totalListings": obj.get("totalListings") if obj.get("totalListings") is not None else 0,
            "dataByPropertyType": [RentcastRentcastMarketStatistics200ResponseSaleDataDataByPropertyTypeInner.from_dict(_item) for _item in obj["dataByPropertyType"]] if obj.get("dataByPropertyType") is not None else None,
            "dataByBedrooms": [RentcastRentcastMarketStatistics200ResponseSaleDataDataByBedroomsInner.from_dict(_item) for _item in obj["dataByBedrooms"]] if obj.get("dataByBedrooms") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


