# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RentcastRentEstimateLongTerm200Response(BaseModel):
    """
    RentcastRentEstimateLongTerm200Response
    """ # noqa: E501
    rent: Optional[StrictInt] = 0
    rent_range_low: Optional[StrictInt] = Field(default=0, alias="rentRangeLow")
    rent_range_high: Optional[StrictInt] = Field(default=0, alias="rentRangeHigh")
    latitude: Optional[Union[StrictFloat, StrictInt]] = 0
    longitude: Optional[Union[StrictFloat, StrictInt]] = 0
    comparables: Optional[List[RentcastRentcastRentEstimateLongTerm200ResponseComparablesInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["rent", "rentRangeLow", "rentRangeHigh", "latitude", "longitude", "comparables"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastRentEstimateLongTerm200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in comparables (list)
        _items = []
        if self.comparables:
            for _item_comparables in self.comparables:
                if _item_comparables:
                    _items.append(_item_comparables.to_dict())
            _dict['comparables'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastRentEstimateLongTerm200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rent": obj.get("rent") if obj.get("rent") is not None else 0,
            "rentRangeLow": obj.get("rentRangeLow") if obj.get("rentRangeLow") is not None else 0,
            "rentRangeHigh": obj.get("rentRangeHigh") if obj.get("rentRangeHigh") is not None else 0,
            "latitude": obj.get("latitude") if obj.get("latitude") is not None else 0,
            "longitude": obj.get("longitude") if obj.get("longitude") is not None else 0,
            "comparables": [RentcastRentcastRentEstimateLongTerm200ResponseComparablesInner.from_dict(_item) for _item in obj["comparables"]] if obj.get("comparables") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


