# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RentcastRentEstimateLongTerm200ResponseComparablesInner(BaseModel):
    """
    RentcastRentEstimateLongTerm200ResponseComparablesInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["7306-Kingsland-Dr,-San-Antonio,-TX-78244"]})
    formatted_address: Optional[StrictStr] = Field(default=None, alias="formattedAddress", json_schema_extra={"examples": ["7306 Kingsland Dr, San Antonio, TX 78244"]})
    address_line1: Optional[StrictStr] = Field(default=None, alias="addressLine1", json_schema_extra={"examples": ["7306 Kingsland Dr"]})
    address_line2: Optional[StrictStr] = Field(default=None, alias="addressLine2")
    city: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["San Antonio"]})
    state: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["TX"]})
    state_fips: Optional[StrictStr] = Field(default=None, alias="stateFips", json_schema_extra={"examples": ["48"]})
    zip_code: Optional[StrictStr] = Field(default=None, alias="zipCode", json_schema_extra={"examples": ["78244"]})
    county: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Bexar"]})
    county_fips: Optional[StrictStr] = Field(default=None, alias="countyFips", json_schema_extra={"examples": ["029"]})
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [29.473782]})
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [-98.344684]})
    property_type: Optional[StrictStr] = Field(default=None, alias="propertyType", json_schema_extra={"examples": ["Single Family"]})
    bedrooms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [3]})
    bathrooms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [2]})
    square_footage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="squareFootage", json_schema_extra={"examples": [1835]})
    lot_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lotSize", json_schema_extra={"examples": [7405]})
    year_built: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="yearBuilt", json_schema_extra={"examples": [1997]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Inactive"]})
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [1627]})
    listing_type: Optional[StrictStr] = Field(default=None, alias="listingType", json_schema_extra={"examples": ["Standard"]})
    listed_date: Optional[datetime] = Field(default=None, alias="listedDate", json_schema_extra={"examples": ["2025-02-06T00:00:00.000Z"]})
    removed_date: Optional[datetime] = Field(default=None, alias="removedDate", json_schema_extra={"examples": ["2025-02-07T00:00:00.000Z"]})
    last_seen_date: Optional[datetime] = Field(default=None, alias="lastSeenDate", json_schema_extra={"examples": ["2025-02-06T05:09:03.727Z"]})
    days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="daysOnMarket", json_schema_extra={"examples": [1]})
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [0.4359]})
    days_old: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="daysOld", json_schema_extra={"examples": [210]})
    correlation: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [0.9873]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "formattedAddress", "addressLine1", "addressLine2", "city", "state", "stateFips", "zipCode", "county", "countyFips", "latitude", "longitude", "propertyType", "bedrooms", "bathrooms", "squareFootage", "lotSize", "yearBuilt", "status", "price", "listingType", "listedDate", "removedDate", "lastSeenDate", "daysOnMarket", "distance", "daysOld", "correlation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastRentEstimateLongTerm200ResponseComparablesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastRentEstimateLongTerm200ResponseComparablesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "formattedAddress": obj.get("formattedAddress"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "stateFips": obj.get("stateFips"),
            "zipCode": obj.get("zipCode"),
            "county": obj.get("county"),
            "countyFips": obj.get("countyFips"),
            "latitude": obj.get("latitude") if obj.get("latitude") is not None else None,
            "longitude": obj.get("longitude") if obj.get("longitude") is not None else None,
            "propertyType": obj.get("propertyType"),
            "bedrooms": obj.get("bedrooms") if obj.get("bedrooms") is not None else None,
            "bathrooms": obj.get("bathrooms") if obj.get("bathrooms") is not None else None,
            "squareFootage": obj.get("squareFootage") if obj.get("squareFootage") is not None else None,
            "lotSize": obj.get("lotSize") if obj.get("lotSize") is not None else None,
            "yearBuilt": obj.get("yearBuilt") if obj.get("yearBuilt") is not None else None,
            "status": obj.get("status"),
            "price": obj.get("price") if obj.get("price") is not None else None,
            "listingType": obj.get("listingType"),
            "listedDate": obj.get("listedDate"),
            "removedDate": obj.get("removedDate"),
            "lastSeenDate": obj.get("lastSeenDate"),
            "daysOnMarket": obj.get("daysOnMarket") if obj.get("daysOnMarket") is not None else None,
            "distance": obj.get("distance") if obj.get("distance") is not None else None,
            "daysOld": obj.get("daysOld") if obj.get("daysOld") is not None else None,
            "correlation": obj.get("correlation") if obj.get("correlation") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


