# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RentcastPropertyRecords200ResponseInnerHistory(BaseModel):
    """
    RentcastPropertyRecords200ResponseInnerHistory
    """ # noqa: E501
    var_2004_06_16: Optional[RentcastRentcastPropertyRecords200ResponseInnerHistory20040616] = Field(default=None, alias="2004-06-16")
    var_2017_10_19: Optional[RentcastRentcastPropertyRecords200ResponseInnerHistory20171019] = Field(default=None, alias="2017-10-19")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["2004-06-16", "2017-10-19"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastPropertyRecords200ResponseInnerHistory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_2004_06_16
        if self.var_2004_06_16:
            _dict['2004-06-16'] = self.var_2004_06_16.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_2017_10_19
        if self.var_2017_10_19:
            _dict['2017-10-19'] = self.var_2017_10_19.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastPropertyRecords200ResponseInnerHistory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "2004-06-16": RentcastRentcastPropertyRecords200ResponseInnerHistory20040616.from_dict(obj["2004-06-16"]) if obj.get("2004-06-16") is not None else None,
            "2017-10-19": RentcastRentcastPropertyRecords200ResponseInnerHistory20171019.from_dict(obj["2017-10-19"]) if obj.get("2017-10-19") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


