# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: support@rentcast.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner(BaseModel):
    """
    RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner
    """ # noqa: E501
    property_type: Optional[StrictStr] = Field(default=None, alias="propertyType")
    average_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="averagePrice")
    median_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="medianPrice")
    min_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="minPrice")
    max_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="maxPrice")
    average_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="averagePricePerSquareFoot")
    median_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="medianPricePerSquareFoot")
    min_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="minPricePerSquareFoot")
    max_price_per_square_foot: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="maxPricePerSquareFoot")
    average_square_footage: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="averageSquareFootage")
    median_square_footage: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="medianSquareFootage")
    min_square_footage: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="minSquareFootage")
    max_square_footage: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="maxSquareFootage")
    average_days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="averageDaysOnMarket")
    median_days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="medianDaysOnMarket")
    min_days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="minDaysOnMarket")
    max_days_on_market: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="maxDaysOnMarket")
    new_listings: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="newListings")
    total_listings: Optional[Union[StrictFloat, StrictInt]] = Field(default=, alias="totalListings")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["propertyType", "averagePrice", "medianPrice", "minPrice", "maxPrice", "averagePricePerSquareFoot", "medianPricePerSquareFoot", "minPricePerSquareFoot", "maxPricePerSquareFoot", "averageSquareFootage", "medianSquareFootage", "minSquareFootage", "maxSquareFootage", "averageDaysOnMarket", "medianDaysOnMarket", "minDaysOnMarket", "maxDaysOnMarket", "newListings", "totalListings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RentcastMarketStatistics200ResponseSaleDataHistory202506DataByPropertyTypeInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "propertyType": obj.get("propertyType"),
            "averagePrice": obj.get("averagePrice") if obj.get("averagePrice") is not None else ,
            "medianPrice": obj.get("medianPrice") if obj.get("medianPrice") is not None else ,
            "minPrice": obj.get("minPrice") if obj.get("minPrice") is not None else ,
            "maxPrice": obj.get("maxPrice") if obj.get("maxPrice") is not None else ,
            "averagePricePerSquareFoot": obj.get("averagePricePerSquareFoot") if obj.get("averagePricePerSquareFoot") is not None else ,
            "medianPricePerSquareFoot": obj.get("medianPricePerSquareFoot") if obj.get("medianPricePerSquareFoot") is not None else ,
            "minPricePerSquareFoot": obj.get("minPricePerSquareFoot") if obj.get("minPricePerSquareFoot") is not None else ,
            "maxPricePerSquareFoot": obj.get("maxPricePerSquareFoot") if obj.get("maxPricePerSquareFoot") is not None else ,
            "averageSquareFootage": obj.get("averageSquareFootage") if obj.get("averageSquareFootage") is not None else ,
            "medianSquareFootage": obj.get("medianSquareFootage") if obj.get("medianSquareFootage") is not None else ,
            "minSquareFootage": obj.get("minSquareFootage") if obj.get("minSquareFootage") is not None else ,
            "maxSquareFootage": obj.get("maxSquareFootage") if obj.get("maxSquareFootage") is not None else ,
            "averageDaysOnMarket": obj.get("averageDaysOnMarket") if obj.get("averageDaysOnMarket") is not None else ,
            "medianDaysOnMarket": obj.get("medianDaysOnMarket") if obj.get("medianDaysOnMarket") is not None else ,
            "minDaysOnMarket": obj.get("minDaysOnMarket") if obj.get("minDaysOnMarket") is not None else ,
            "maxDaysOnMarket": obj.get("maxDaysOnMarket") if obj.get("maxDaysOnMarket") is not None else ,
            "newListings": obj.get("newListings") if obj.get("newListings") is not None else ,
            "totalListings": obj.get("totalListings") if obj.get("totalListings") is not None else 
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


