name: Generate and Publish Rentcast API Package

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install twine wheel setuptools
          npm install @openapitools/openapi-generator-cli -g

      - name: Download OpenAPI spec
        id: download_spec
        run: bash scripts/download_openapi_spec.sh

      - name: Generate package
        run: bash scripts/generate_package.sh

      - name: Build and publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash scripts/build_and_publish.sh
