name: Generate and Publish Rentcast API Package

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install twine wheel
          npm install @openapitools/openapi-generator-cli -g

      - name: Download and compare OpenAPI spec
        id: compare_spec
        run: |
          bash scripts/download_openapi_spec.sh
          if [ -f "openapi_spec.json.old" ]; then
            if cmp -s "openapi_spec.json" "openapi_spec.json.old"; then
              echo "No changes detected in the OpenAPI spec."
              echo "::set-output name=changed::false"
            else
              echo "Changes detected in the OpenAPI spec."
              echo "::set-output name=changed::true"
            fi
          else
            echo "No previous OpenAPI spec found. Treating as a change."
            echo "::set-output name=changed::true"
          fi
          mv openapi_spec.json openapi_spec.json.old

      - name: Generate package
        if: steps.compare_spec.outputs.changed == 'true'
        run: bash scripts/generate_package.sh

      - name: Build and publish package
        if: steps.compare_spec.outputs.changed == 'true'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash scripts/build_and_publish.sh
