name: Update OpenAPI Spec

on:
  schedule:
    - cron: '0 0 * * *' # Every night at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install poetry
          npm install @openapitools/openapi-generator-cli -g

      - name: Download OpenAPI spec
        run: bash scripts/download_openapi_spec.sh

      - name: Generate package
        run: bash scripts/generate_package.sh

      - name: Check for changes
        id: git-check
        run: |
          git add rentcast_client/ openapi_spec.json
          git diff --staged --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "feat: update client to latest Rentcast API spec [skip ci]"
          git push
